### ISSUE TITLE
The `pgsql` driver is not supported at this time.

### ISSUE THREAD

**Issue by ldavidsp** [bennett-treptow/laravel-migration-generator#89] opened 2024-05-01 04:29 UTC
![image](https://github.com/bennett-treptow/laravel-migration-generator/assets/44006503/e6caf9a6-a043-4186-ada3-a097ff9c9a90)

**Comment by bennett-treptow** [comment] 2024-05-24 00:33
That is accurate; we currently do not support postgres. You are free to contribute, and there is a draft PR that was opened but never finished with https://github.com/bennett-treptow/laravel-migration-generator/pull/57 that you are free to try.

Closing this as not a bug, but a known limitation at this point in time.

**Closed by bennett-treptow** 2024-05-24 00:33 UTC
